USE museo_auditoria;

INSERT INTO auditoria_codigos_membresia (
    id_comprador,
    fecha_registro,
    codigo_seguridad,
    correo_envio,
    estado
) VALUES (
    1,
    '2026-06-04 08:00:00',
    'MK8X2Q9Z',
    'comprador1@correo.com',
    'EMITIDO'
);

INSERT INTO auditoria_codigos_membresia (
    id_comprador,
    fecha_registro,
    codigo_seguridad,
    correo_envio,
    estado
) VALUES (
    1,
    '2026-06-04 10:15:00',
    'Q7LM2V8P',
    'comprador1@correo.com',
    'EMITIDO'
);

INSERT INTO auditoria_codigos_membresia (
    id_comprador,
    fecha_registro,
    codigo_seguridad,
    correo_envio,
    estado
) VALUES (
    2,
    '2026-06-04 09:30:00',
    'A9T4N6K1',
    'comprador2@correo.com',
    'EMITIDO'
);

INSERT INTO auditoria_codigos_membresia (
    id_comprador,
    fecha_registro,
    codigo_seguridad,
    correo_envio,
    estado
) VALUES (
    3,
    '2026-06-04 11:45:00',
    'X3C9R2HF',
    'comprador3@correo.com',
    'EMITIDO'
);

INSERT INTO auditoria_codigos_membresia (
    id_comprador,
    fecha_registro,
    codigo_seguridad,
    correo_envio,
    estado
) VALUES (
    3,
    '2026-06-04 12:05:00',
    'L5V8Q1MN',
    'comprador3@correo.com',
    'EMITIDO'
);
